### ISSUE TITLE
Update to io.js 2.3.3 (Critical security release)

### ISSUE THREAD

**Issue by frankhale** [atom/node#10]
Since people are consuming io.js using Electron and people are looking there at issues I've elected to post this issue there:

https://github.com/atom/electron/issues/2124

NOTE: I can submit a PR but if it's easier for you to merge it then I'll just defer to you.

**Comment by zcbenz** [comment]
Closing as stated in https://github.com/atom/electron/issues/2124#issuecomment-118621289.

**Comment by frankhale** [comment]
Awesome thanks for the explanation!
